# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'SyncData' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  # Pods for SyncData

  target 'SyncDataTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SyncDataUITests' do
    # Pods for testing
  end

end
